name: discover_printers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  charset_converter: ^2.2.1
  cupertino_icons: ^1.0.8
  esc_pos_printer:
    path: ../../
  esc_pos_utils:
    git:
      url: https://github.com/Abdalqader27/esc_pos_utils
      ref: master
  flutter:
    sdk: flutter
  image: ^4.2.0
  intl: ^0.16.1
  path_provider: ^2.1.4
  ping_discover_network: ^0.2.0+1
  qr_flutter: ^4.1.0
  wifi: ^0.1.5
  # esc_pos_utils:
  # path: ../../../esc_pos_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rabbit_black.jpg
